### ISSUE TITLE
Doubt on 'conditions' parameter

### ISSUE THREAD

**Issue by mjm522** [cbfinn/gps#55]
I am unable to find out what exactly is the role of **'conditions' :4** in the hyperparameters file? Could someone please help?

**Comment by wmontgomery4** [comment]
It's maybe poorly named, but `conditions` just refers to the number of experimental conditions, which is typically just the number of initial positions.

**Comment by mjm522** [comment]
Thank you for the reply. Could you please elaborate a little more?
Number of initial positions? Do you mean four different positions (of the robot) from which the same experiment is done parallelly? Or four different start locations of end effector (for e.g. the peg insertion task)?  Why is it done like that? Is is just for the having different views of the world if you are using cov-nets for image processing?

**Comment by wmontgomery4** [comment]
It can refer to different positions of the robot, or different target positions, it depends on how you set up the rest of the hyperparams. It's done like this because that's the point of GPS: we essentially solve the problem locally from M different initial conditions, then use a neural network to combine those local solutions into one global solution.

**Comment by cbfinn** [comment]
Please refer to the paper for basic algorithmic questions:
http://jmlr.org/papers/v17/15-522.html
