### ISSUE TITLE
Catkin version of ROS package & Docker image

### ISSUE THREAD

**Issue by robotsorcerer** [cbfinn/gps#61]
Hey,

Thanks for making this code public. Are there plans to release a docker image of this setup anytime soon? And is there a reason why you guys chose the non-catkinized option for the ros implementation?
It would be nice to have, I think.

**Comment by cbfinn** [comment]
We don't currently have plans to make a docker image of the set-up in the near future, but we would welcome such a contribution!

We chose not to use catkin because there were some people still using ROS fuerte in our lab. I agree that it would be nice.

**Comment by robotsorcerer** [comment]
Thought I should leave the link to the catkinized version of the ROS package here as others might find it useful. https://github.com/lakehanne/gps_catkin

**Comment by cbfinn** [comment]
Thanks!

**Comment by cbfinn** [comment]
I'll leave this issue open for now, until there is a docker image.

**Comment by ahundt** [comment]
I've created the following pull request https://github.com/cbfinn/gps/pull/69 which likely does much of the same. 

@lakehanne I looked at your repository and your work seems to be a separate repository rather than modifying a fork, was that intentional?

**Comment by robotsorcerer** [comment]
Not really. I guess I could have forked chelsea's work and send a PR of my work but this was supposed to be a wip till I finish the docker image. Sadly, I have been busy with upcoming deadlines that I have not paid too much attention to developing the docker image lately. I should be able to get back to it soon though. 

Hey, as per #69 I am not too familiar with Karmic. Have you tested your code with jade and indigo yet? I do not have the time to test now. If you are just hopeful it would work with indigo ot Jade, you might as well just call it a `karmic-devel branch`. 

@cbfinn , would you rather have me send my [indigo repo](https://github.com/lakehanne/gps/tree/master) as a PR to you in the meantime?

**Comment by robotsorcerer** [comment]
Initial docker image here:

  https://hub.docker.com/r/lakehanne/gps/

I can get the box and ros examples to run but the matplotlib window does not update the charts on every system I have tested it on. If anyone can figure out how to do this, it would be appreciated.

The dockerfile for the build is available here:

https://github.com/lakehanne/gps/blob/master/Dockerfile
   
As Mujoco comes with a license, I did not install mujoco on the image. Users can install mujoco if they wish and run the examples.

**UPDATE: 2017-06-08**

Also moved the catkin version [here](https://github.com/service-lab/gps) with support for tensorflow version 1.1.0

**Comment by robotsorcerer** [comment]
I found a fix for the `Bad Drawable error` I was getting earlier. It seems we needed to export the environmental variable for QT or KDE.

Doing this fixes the drawable errors:
 
#### Fix
Add this line `QT_X11_NO_MITSHM=1` in `~/.bashrc` or export the environmental variable from terminal:

`export QT_X11_NO_MITSHM=1`

Then run the bash script for the examples. @cbfinn, I think you can close this issue now.

**Comment by ahundt** [comment]
@lakehanne I think the changes would need to be merged in to this repository for closing this to be appropriate.

**Comment by ruinianxu** [comment]
Hi lakehanne,
I wonder how did you install pr2 package. Since there is no official released pr2 package which contains all related needed packages, my strategy is to separately install binary pr2 packages like pr2_simulator. I tried source code but there was still some dependency problem. Since you are also using ros indigo, really appreciate it if you can give me some suggestions.

**Comment by lakehanne** [comment]
The pr2 package is shipped in ubuntu 14.04 repos as part of the ROS packages.

cd to the manifest folder and do

‘rosdep install -from-paths . -ry ‘

Sincerely,
Lekan

“A graduate student’s job is to turn his advisor’s bad ideas into good ones.” ~ Pedro Domingos

**Comment by ruinianxu** [comment]
Thank you for your reply!
Like what you said, firstly I tried to install ros-indigo-pr2-desktop
according to website http://wiki.ros.org/Robots/PR2/indigo. However there
is no package named ros-indigo-pr2-desktop. Then I had to install
pr2-related packages separately. But when launching
*pr2_gazebo_no_controller.launch, I met the problem of gazebo_worlds not
found. After I installed several packages like ros-indigo-pr2-simulator and
ros-indigo-gazebo-xxx , problem still exists. After checked pr2-simulator
package, I found in pr2_gazebo there is a launch file called
pr2_gazebo_empty_world something like that. After modifying launch file,
there was other errors. *

*It seems be a silly problem since it is just pr2 stuffs. Nothing related
to gps or caffe. Since it is a pure pr2 problem, I really want to know what
ros-indigo-pr2 packages you installed that help you run launch file since I
am assuming there should be a pr2 package that contains all control and
simulator-related packages and after installing it, I don't need to install
other packages. *

**Comment by huiwenzhang** [comment]
@lakehanne  Hi, thanks for your job. It's really helpful. I want to know which version of your images is the latest on docker hub? You have gps-v0.0.2 and v0.1.1 , but  it not clear about the difference.

**Comment by robotsorcerer** [comment]
I can’t remember now but I think it must be the one with the highest tag.



-----
Sincerely,
Lékan

"The past was erased, the erasure was forgotten, the lie became the truth." 

--George Orwell

**Comment by huiwenzhang** [comment]
@lakehanne  Ok, I will try it.
